### ISSUE TITLE
Add Unique ID to Checkout Fieldset

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/edd-upload-file#15]
Hard to target for styling with a duplicate ID of `edd_checkout_user_info` on the fieldset that is added (it's also invalid HTML). Would be nice if it was unique or had an accompanying class.

**Comment by spencerfinnell** [comment]
I would also highly suggest removing the `<hr />` tag. Themes can add style elements/borders themselves. 

Don't make me live like this!

```css
#edd_checkout_user_info {
	legend + .edd-description + hr {
		display: none;
	}
}
```
